First attempt at creating queries for LSC tasks
silvanheller/temporal-query-evaluation pull request #1
Opened 2022-04-14 08:00 UTC by benzvera

Created a task pool for lifelog queries and implemented the first one. Tags, text-co-embeddings and boolean searches can be implemented as objects now.

2022-04-19 08:33 UTC, silvanheller requested changes
Looks promising, thanks for the work! I left some comments. One general feedback:
- The `checkstyle-idea.xml` and `google-java-format.xml` files should not be in the repo, as we're using ktlint

2022-04-19 08:33 UTC, silvanheller commented on src/main/kotlin/com/github/silvanheller/tempAlgEval/main/SpecsBuilder.kt
> +                            listOf(Pool.result) as List<Result>,
I think this is a consequence of declaring the `result` in `Pool` as `Any`.  I would simply declare it as `List<Result>` (which is then just length 1 for VBS-tasks), which leads to clearer code and you don't have to cast to List<> here

2022-04-19 08:33 UTC, silvanheller commented on src/main/kotlin/com/github/silvanheller/tempAlgEval/main/TaskPoolLSC.kt
> +                                0F,                 // start and end are always 0
This needs to specify start and end, as in LSC tasks we're looking for specific events within the day, and not just the whole day.

2022-04-19 08:33 UTC, silvanheller commented on src/main/kotlin/com/github/silvanheller/tempAlgEval/main/TaskPoolLSC.kt
> +                                                                                        "driving"
The Tag descriptions and name are not necessary for retrieval

2022-04-19 08:33 UTC, silvanheller commented on src/main/kotlin/com/github/silvanheller/tempAlgEval/main/TaskPoolLSC.kt
> +                                                                        QueryCategories.image,
image seems incorrect to me :) You probably want to add a new a category called `filter`, which is what was previously used for VBS interaction logging.

2022-04-19 08:33 UTC, silvanheller commented on src/main/kotlin/com/github/silvanheller/tempAlgEval/model/enums.kt
> +    jointEmbedding,         //
This means text is mapped to an image / video representation space

2022-04-19 08:33 UTC, silvanheller commented on src/main/kotlin/com/github/silvanheller/tempAlgEval/model/enums.kt
> +    LSC
This should probably specify the years (LSC2018 & 2019 used the same dataset, 2020 & 2021 used the same dataset, and 2022 will use a new dataset).

2022-04-19 08:33 UTC, silvanheller commented on src/main/kotlin/com/github/silvanheller/tempAlgEval/model/models.kt
> +open class QueryTermType()
I don't fully understand the reasoning behind this refactoring, maybe we can discuss this offline

2022-04-19 08:33 UTC, silvanheller commented on src/main/kotlin/com/github/silvanheller/tempAlgEval/query/websocket/QueryBuilder.kt
>                      if (cineastType == CineastQueryTermType.TAG) {
use `when` also for CineastTypes

2022-04-19 08:33 UTC, silvanheller commented on src/main/kotlin/com/github/silvanheller/tempAlgEval/scoring/algorithms/vitrivr/VitrivrScoringAlgorithm.kt
> +    override fun scoreInternal(dataset: Dataset): ResultScoreTuple {
I think an easier structure would be to have the `dataset` as a parameter for the `ScoringAlgorithm`, and then the `parseObjectId` method could take `dataset` as a parameter which you can access with `this.dataset`. This means you don't have to duplicate the code handling parsing for different datasets across the scoring algorithms.

2022-04-21 13:09 UTC, benzvera commented on src/main/kotlin/com/github/silvanheller/tempAlgEval/main/TaskPoolLSC.kt
> +                                                                                        "driving"
The tag name is important for transforming the tag into a text co-embedding

2022-04-25 13:57 UTC, silvanheller requested changes

2022-05-10 16:34 UTC, merged